# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0ac756b9def96905f183e34b5e88597d4bb220273e96861aa9bdd59de2c909113b09b8a6cffa708b8bb29b028e5587d290107d80ae4b12deebd41790fad9e0b6

test:
  secret_key_base: 31b0bbe26d03ae3a0b941f472717037d8ae5bbb5a9018d43c161aaf288a7ffc7cf1ff46bb5a1947de64e42eb53a5e4cbebf9abff3f97ad69ca09975b00879e20

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
